CREATE TABLE kpis (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  quarter TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  weight INTEGER NOT NULL DEFAULT 0,
  target_metric TEXT NOT NULL DEFAULT '',
  parent_kpi_id INTEGER DEFAULT NULL,
  progress_q1 INTEGER NOT NULL DEFAULT 0,
  progress_q2 INTEGER NOT NULL DEFAULT 0,
  progress_q3 INTEGER NOT NULL DEFAULT 0,
  progress_q4 INTEGER NOT NULL DEFAULT 0,
  annual_progress INTEGER NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (parent_kpi_id) REFERENCES kpis(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_kpis_parent_id ON kpis(parent_kpi_id);
