CREATE TABLE achievements (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  quarter TEXT NOT NULL,
  raw_text TEXT NOT NULL,
  enhanced_text TEXT NOT NULL DEFAULT '',
  category TEXT NOT NULL DEFAULT '',
  impact_note TEXT NOT NULL DEFAULT '',
  kpi_id INTEGER,
  status TEXT NOT NULL DEFAULT 'draft',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (kpi_id) REFERENCES kpis(id) ON DELETE SET NULL
);
